[custom]
;ä¸è¦éšæ„æ”¹å˜å…³é”®å­—ï¼Œå¦åˆ™ä¼šå¯¼è‡´å‡ºé”™
;acl4SSRè§„åˆ™

;å»å¹¿å‘Šï¼šæ”¯æŒ
;è‡ªåŠ¨æµ‹é€Ÿï¼šæ”¯æŒ
;å¾®è½¯åˆ†æµï¼šæ”¯æŒ
;è‹¹æœåˆ†æµï¼šæ”¯æŒ
;å¢å¼ºä¸­å›½IPæ®µï¼šæ”¯æŒ
;å¢å¼ºå›½å¤–GFWï¼šæ”¯æŒ

;è®¾ç½®è§„åˆ™æ ‡å¿—ä½
ruleset=ğŸ® æ¸¸æˆå¹³å°,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Epic_domain.yaml
ruleset=ğŸ® æ¸¸æˆå¹³å°,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Sony_domain.yaml
ruleset=ğŸ® æ¸¸æˆå¹³å°,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Steam_domain.yaml
ruleset=ğŸ® æ¸¸æˆå¹³å°,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Nintendo_domain.yaml
ruleset=ğŸ® æ¸¸æˆå¹³å°,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Nintendo_ipcidr.yaml,no-resolve
ruleset=ğŸ¥ Netflix,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Netflix_domain.yaml
ruleset=ğŸ¥ Netflix,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/NetflixIP_ipcidr.yaml,no-resolve
ruleset=ğŸ¥ Netflix,clash-classic:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Netflix_classical.yaml
ruleset=ğŸ¥ Disney+,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/DisneyPlus_domain.yaml
ruleset=ğŸ¤– OpenAI,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/openai_domain.yaml
ruleset=ğŸ¤– OpenAI,clash-classic:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/openai_classical.yaml
ruleset=ğŸŒ å›½å¤–åª’ä½“,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ProxyMedia_domain.yaml
ruleset=ğŸŒ å›½å¤–åª’ä½“,clash-classic:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ProxyMedia_classical.yaml
ruleset=ğŸš€ èŠ‚ç‚¹é€‰æ‹©,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/proxies_domain.yaml
ruleset=ğŸš€ èŠ‚ç‚¹é€‰æ‹©,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/proxies_ipcidr.yaml,no-resolve
ruleset=ğŸš€ èŠ‚ç‚¹é€‰æ‹©,clash-classic:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/proxies_classical.yaml
ruleset=ğŸ’¬ å¾®ä¿¡,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/wechat_domain.yaml
ruleset=ğŸ’¬ å¾®ä¿¡,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/wechat_ipcidr.yaml,no-resolve
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ChinaDomain_domain.yaml
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-classic:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ChinaDomain_classical.yaml
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ChinaDomain_ipcidr.yaml,no-resolve
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ChinaCompanyIp_ipcidr.yaml,no-resolve
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/Download_domain.yaml
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/direct_domain.yaml
;ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/LocalAreaNetwork_domain.yaml
;ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/LocalAreaNetwork_ipcidr.yaml,no-resolve
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/UnBan_domain.yaml
ruleset=ğŸ›‘ å¹¿å‘Šæ‹¦æˆª,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanAD_domain.yaml
ruleset=ğŸ›‘ å¹¿å‘Šæ‹¦æˆª,clash-classic:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanAD_classical.yaml
ruleset=ğŸƒ åº”ç”¨å‡€åŒ–,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanProgramAD_domain.yaml
ruleset=ğŸƒ åº”ç”¨å‡€åŒ–,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanProgramAD_ipcidr.yaml,no-resolve
ruleset=ğŸ† AdBlock,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanEasyList_domain.yaml
ruleset=ğŸ† AdBlock,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanEasyList_ipcidr.yaml,no-resolve
ruleset=ğŸ† AdBlock,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanEasyListChina_domain.yaml
ruleset=ğŸ† AdBlock,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanEasyListChina_ipcidr.yaml,no-resolve
ruleset=ğŸ† AdBlock,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/ad_domain.yaml
ruleset=ğŸ›¡ï¸ éšç§é˜²æŠ¤,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanEasyPrivacy_domain.yaml
ruleset=ğŸ›¡ï¸ éšç§é˜²æŠ¤,clash-ipcidr:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/BanEasyPrivacy_ipcidr.yaml,no-resolve
ruleset=ğŸ¯ å…¨çƒç›´è¿,clash-domain:https://raw.githubusercontent.com/chinnsenn/ClashCustomRule/master/providers/GoogleCN_domain.yaml
ruleset=ğŸ¯ å…¨çƒç›´è¿,[]GEOIP,CN
ruleset=ğŸŸ æ¼ç½‘ä¹‹é±¼,[]FINAL
;è®¾ç½®è§„åˆ™æ ‡å¿—ä½

;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½
custom_proxy_group=ğŸš€ èŠ‚ç‚¹é€‰æ‹©`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸ”¯ æ•…éšœè½¬ç§»`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨
custom_proxy_group=ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`select`.*
custom_proxy_group=â™»ï¸ è‡ªåŠ¨é€‰æ‹©`url-test`((^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:æ¸¯|é¦™æ¸¯|HongKong|HK|Hong Kong|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan|ç¾|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z])|KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)).*$))`http://www.gstatic.com/generate_204`300,100
;custom_proxy_group=â™»ï¸ è‡ªåŠ¨é€‰æ‹©`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9])))`http://www.gstatic.com/generate_204`300,100
custom_proxy_group=ğŸ”¯ æ•…éšœè½¬ç§»`fallback`.*`http://www.gstatic.com/generate_204`300,100
custom_proxy_group=ğŸ“¹ YouTube`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`.*
custom_proxy_group=ğŸ¤– OpenAI`select`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨
custom_proxy_group=ğŸ¥ Netflix`select`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`.*
custom_proxy_group=ğŸ¥ Disney+`select`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`.*
custom_proxy_group=ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:æ¸¯|é¦™æ¸¯|HongKong|HK|Hong Kong)).*$)`http://www.gstatic.com/generate_204`300,100
custom_proxy_group=ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)).*$)`http://www.gstatic.com/generate_204`300,100
custom_proxy_group=ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:ç¾|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|United States|(?<![a-zA-Z])US(?![a-zA-Z])|(?<![a-zA-Z])USA(?![a-zA-Z])|(?<![a-zA-Z])USD(?![a-zA-Z]))).*$)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)).*$)`http://www.gstatic.com/generate_204`300,100
custom_proxy_group=ğŸŒ å›½å¤–åª’ä½“`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸ® æ¸¸æˆå¹³å°`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ’¬ å¾®ä¿¡`select`[]DIRECT`[]REJECT`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ¯ å…¨çƒç›´è¿`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©
custom_proxy_group=ğŸ›‘ å¹¿å‘Šæ‹¦æˆª`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸƒ åº”ç”¨å‡€åŒ–`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸ† AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸ›¡ï¸ éšç§é˜²æŠ¤`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸŸ æ¼ç½‘ä¹‹é±¼`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹-è‡ªåŠ¨`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½

enable_rule_generator=true
overwrite_original_rules=true
skip_failed_links=true

exclude_remarks=(IPV6|é‡ç½®|æµé‡|ç”¨æˆ·|æœ¬ç«™|æ¼æ´|æ°¸ä¹…è™šé€šè·¯|è½¦|é‚€|å…ç¿»|é‚€è¯·|eevpn|åŸŸå|æœºåœº|åˆ·æ–°|ç¦æ­¢|è¶…æ—¶|è¿‡æœŸ|å¤‡ç”¨ç™»å½•|è®¡åˆ’|é¢æ¿|å¿˜è®°|åˆ°æœŸ|å¥—é¤|å®˜ç½‘|æ›´å¤š|å…³æ³¨|25å€|http|ç½‘å€|å‘å¸ƒ|å¢åŠ |æŒç»­|æ¸ é“|è´­ä¹°|QQ|Ins|äºŒæ‰‹)

;luck
